name: Copilot Review Trigger

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  trigger-copilot-review:
    name: Trigger Copilot Review
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/copilot-review')
    
    steps:
      - name: Add Copilot as Reviewer
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Requesting Copilot code review...\n\nTo manually add Copilot as a reviewer, go to the "Reviewers" section and type `@copilot`.'
            });
            
            console.log('Copilot review triggered via comment');
