name: Test Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show all event data
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Comment: ${{ github.event.comment.body }}"
          echo "Issue PR: ${{ github.event.issue.pull_request }}"
          
      - name: Test
        if: contains(github.event.comment.body, '/test')
        run: echo "Trigger works!"
